### ISSUE TITLE
请问，编译成功后，点击start，允许了蓝牙被发现，然后其他设备可以扫描到peripheral MK，连接后马上断开了

### ISSUE THREAD

**Issue by jane00** [LiangLuDev/HidPeripheral#2]
没有办法开启为鼠标或者键盘，是哪里的问题？ 用两部手机，Android 12，Android P，两个版本的系统，表现一样。谢谢。

**Comment by LiangLuDev** [comment]
是因为很多ROM的一个配置默认是false，需要修改ROM才行。
具体请看「Notice」部分
